[mcp_servers.better-t-stack]
command = "pnpm"
args = ["dlx", "create-better-t-stack@latest", "mcp"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.nuxt]
type = "http"
url = "https://nuxt.com/mcp"

[mcp_servers.nuxt-ui]
type = "http"
url = "https://ui.nuxt.com/mcp"

[mcp_servers.neon]
type = "http"
url = "https://mcp.neon.tech/mcp"

[mcp_servers.better-auth]
type = "http"
url = "https://mcp.inkeep.com/better-auth/mcp"
