import Zai from "~/components/icon/Zai.vue";
import type { BuiltinProviderDef } from "~/types/providers";

export const BUILTIN_PROVIDERS: readonly BuiltinProviderDef[] = [
  {
    id: "minimax",
    name: "MiniMax",
    icon: "i-simple-icons-minimax",
    hasBaseUrl: false,
    defaultBaseUrl: "https://api.minimaxi.com/v1",
    keyPlaceholder: "sk-...",
    apiKeyUrl: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    urlPlaceholder: "https://api.minimaxi.com/v1",
    fetchMode: "openai",
  },
  {
    id: "qwen",
    name: "Qwen",
    icon: "i-simple-icons-qwen",
    hasBaseUrl: true,
    defaultBaseUrl: "https://dashscope-us.aliyuncs.com/compatible-mode/v1",
    keyPlaceholder: "sk-...",
    apiKeyUrl: "https://modelstudio.console.alibabacloud.com/apikey",
    urlPlaceholder: "https://dashscope-us.aliyuncs.com/compatible-mode/v1",
    fetchMode: "openai",
  },
  {
    id: "zai",
    name: "Z.ai",
    icon: Zai,
    hasBaseUrl: true,
    defaultBaseUrl: "https://api.z.ai/api/paas/v4",
    keyPlaceholder: "...",
    apiKeyUrl: "https://z.ai/manage-apikey/apikey-list",
    urlPlaceholder: "https://api.z.ai/api/paas/v4",
    fetchMode: "openai",
  },
  {
    id: "xiaomimimo",
    name: "Xiaomi MiMo",
    icon: "i-simple-icons-xiaomi",
    hasBaseUrl: true,
    defaultBaseUrl: "https://api.xiaomimimo.com/v1",
    keyPlaceholder: "sk-... or tp-...",
    apiKeyUrl: "https://platform.xiaomimimo.com/",
    urlPlaceholder: "https://api.xiaomimimo.com/v1",
    fetchMode: "openai",
  },
  {
    id: "doubao",
    name: "Doubao",
    icon: "i-simple-icons-bytedance",
    hasBaseUrl: false,
    defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    keyPlaceholder: "...",
    apiKeyUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    urlPlaceholder: "https://ark.cn-beijing.volces.com/api/v3",
    fetchMode: "openai",
  },
  {
    id: "hunyuan",
    name: "Tencent Hunyuan",
    icon: "i-lucide-circle-dot",
    hasBaseUrl: false,
    defaultBaseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    keyPlaceholder: "...",
    apiKeyUrl: "https://console.cloud.tencent.com/hunyuan/api-key",
    urlPlaceholder: "https://api.hunyuan.cloud.tencent.com/v1",
    fetchMode: "openai",
  },
  {
    id: "longcat",
    name: "Meituan LongCat",
    icon: "i-simple-icons-meituan",
    hasBaseUrl: true,
    defaultBaseUrl: "https://api.longcat.chat/openai/v1",
    keyPlaceholder: "...",
    apiKeyUrl: "https://longcat.chat/platform/api_keys",
    urlPlaceholder: "https://api.longcat.chat/openai/v1",
    fetchMode: "openai",
  },
  {
    id: "spark",
    name: "iFLYTEK Spark",
    icon: "i-lucide-sparkles",
    hasBaseUrl: false,
    defaultBaseUrl: "https://spark-api-open.xf-yun.com/v1",
    keyPlaceholder: "...",
    apiKeyUrl: "https://console.xfyun.cn/services/cbm",
    urlPlaceholder: "https://spark-api-open.xf-yun.com/v1",
    fetchMode: "catalog",
  },
  {
    id: "stepfun",
    name: "Jieyue Stepfun",
    icon: "i-lucide-step-forward",
    hasBaseUrl: true,
    defaultBaseUrl: "https://api.stepfun.com/v1",
    keyPlaceholder: "sk-...",
    apiKeyUrl: "https://platform.stepfun.com/interface-key",
    urlPlaceholder: "https://api.stepfun.com/v1",
    fetchMode: "openai",
  },
  {
    id: "wenxin",
    name: "Baidu Wenxin",
    icon: "i-simple-icons-baidu",
    hasBaseUrl: true,
    defaultBaseUrl: "https://qianfan.baidubce.com/v2",
    keyPlaceholder: "bce-v3/...",
    apiKeyUrl: "https://console.bce.baidu.com/qianfan/ais/console/apiKey",
    urlPlaceholder: "https://qianfan.baidubce.com/v2",
    fetchMode: "openai",
  },
  {
    id: "kimi",
    name: "Kimi",
    icon: "i-simple-icons-moonshotai",
    hasBaseUrl: false,
    defaultBaseUrl: "https://api.moonshot.cn/v1",
    keyPlaceholder: "...",
    apiKeyUrl: "https://platform.moonshot.cn/console/api-keys",
    fetchMode: "openai",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    icon: "i-simple-icons-deepseek",
    hasBaseUrl: false,
    defaultBaseUrl: "https://api.deepseek.com",
    keyPlaceholder: "...",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    fetchMode: "openai",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    icon: "i-simple-icons-openrouter",
    hasBaseUrl: false,
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    keyPlaceholder: "...",
    apiKeyUrl: "https://openrouter.ai/settings/keys",
    fetchMode: "openai",
  },
];

export function getBuiltinProviderDef(id: BuiltinProviderDef["id"]) {
  return BUILTIN_PROVIDERS.find((provider) => provider.id === id);
}
